version: '3'
services:
  web:
    image: wordpress:5.4
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - "8080:80"
    volumes:
        - ./:/var/www/html/wp-content/plugins/resmio-button-and-widget
  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
