name: Build and Deploy
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code from github
        uses: actions/checkout@v2
        with:
          path: data-from-github

      - name: Upload to github if branch is deploy-to-production
        uses: actions/upload-artifact@master
#        if: github.ref == 'refs/heads/deploy-to-production'
        with:
          name: reputation-widget-artifact
          path: build
